name: Deploy Terraform
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Terraform Init
        run: terraform init -backend-config=./environments/${{ matrix.environment }}/backend.tfvars
        working-directory: ./environments/${{ matrix.environment }}
      - name: Check directory
        run: ls -l ./environments/dev
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./environments/${{ matrix.environment }}
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/tfplan

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: plan
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Terraform Init
        run: terraform init -backend-config=./environments/${{ matrix.environment }}/backend.tfvars
        working-directory: ./environments/${{ matrix.environment }}
      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan-${{ matrix.environment }}
          path: environments/${{ matrix.environment }}/
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./environments/${{ matrix.environment }}
